version: "3.7"  

networks:
  mynet:
    driver: bridge

services:

  ### NGINX Server #########################################
    nginx:
      build:
        context: ./docker/nginx
      volumes:
        - ./:/usr/share/nginx/html
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
      networks:
        - mynet

### PHP-FPM ##############################################
    php-fpm:
      build:
        context: ./docker/php
        args:
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
          - ./:/var/www
      expose:
        - "9000"
      networks:
        - mynet

  ### MySQL ################################################
    mysql:
      build:
        context: ./docker/mysql
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - mynet

  ### APACHE ################################################
    apache:
      build:
        context: ./docker/apache
      volumes:
        - ./:/var/www/html
      ports:
        - "8000:80"
      networks:
        - mynet