version: "3.7"  

networks:
  mynet:
    driver: bridge

services:

  ### NGINX Server #########################################
    nginx:
      build:
        context: ./docker/nginx
        args:
          # - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
          # - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
          # - CHANGE_SOURCE=${CHANGE_SOURCE}
          - http_proxy
          - https_proxy
          - no_proxy
      # working_dir: /usr/share/nginx/html
      volumes:
        # - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        # - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        # - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        # - ${NGINX_SSL_PATH}:/etc/nginx/ssl
        - ./:/usr/share/nginx/html
          # - type: volume
          #   source: my-data
          #   target: /usr/share/nginx/html
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
      # depends_on:
      #   - php-fpm
      networks:
        - mynet

### PHP-FPM ##############################################
    php-fpm:
      build:
        context: ./docker/php
        args:
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
        # - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
        # - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
          # - type: volume
          #   source: my-data
          #   target: /var/www
          - ./:/var/www
      expose:
        - "9000"
      # extra_hosts:
        # - "dockerhost:${DOCKER_HOST_IP}"
      # environment:
        # - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
        # - DOCKER_HOST=tcp://docker-in-docker:2375
        # - FAKETIME=${PHP_FPM_FAKETIME}
      networks:
        - mynet

  ### MySQL ################################################
    mysql:
      build:
        context: ./docker/mysql
        # args:
        #   - MYSQL_VERSION=${MYSQL_VERSION}
      # environment:
      #   - MYSQL_DATABASE=${MYSQL_DATABASE}
      #   - MYSQL_USER=${MYSQL_USER}
      #   - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      #   - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        # - TZ=${WORKSPACE_TIMEZONE}
      #volumes:
        # - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
        # - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - mynet

  ### APACHE ################################################
    apache:
      build:
        context: ./docker/apache
      volumes:
        - ./:/var/www/html
      ports:
        - "8000:80"
      networks:
        - mynet