version: "3.7"  

networks:
  mynet:
    driver: bridge

services:

  ### NGINX Server #########################################
    nginx:
      build:
        context: ./docker/nginx
      container_name: nginx_caerux
      volumes:
        - ./:/home/projects/demo-docker
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"   #NGINX_HOST_HTTP_PORT is variable in .env file
        - "${NGINX_HOST_HTTPS_PORT}:443"
      depends_on:
        - php-fpm
      networks:
        - mynet

### PHP-FPM ##############################################
    php-fpm:
      build:
        context: ./docker/php
        args:
          - http_proxy
          - https_proxy
          - no_proxy
      container_name: php_fpm_caerux
      volumes:
          - ./:/var/www
      expose:
        - "9000"
      networks: 
        - mynet

  ### MySQL ################################################
    mysql:
      build:
        context: ./docker/mysql
      container_name: mysql_caerux
      environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=true
      volumes:
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
        - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - mynet

  # # IF YOU WANT TO USE APACHE FOR WEB PROXY, YOU WILL REMOVE COMMENT 
  # # APACHE ################################################
  #   apache:
  #     build:
  #       context: ./docker/apache
  #     container_name: apache_caerux
  #     volumes:
  #       - ./:/var/www/html
  #     ports:
  #       - "8000:80"
  #     networks:
  #       - mynet